# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Matt's blog
tagline:             'random notes to self'
description:         'Matts random collection of notes to self'
url:                 http://mjh-test1.github.io
baseurl:             ''
paginate:            5
ga-id:               UA-70518210-1
excerpt_separator:   <!--excerpt-->


# About/contact
author:
  name:              Matt
  url:               http://mjh-test1.github.io
  email:             somewheresometime@mailinator.com
  twitter:           matt_j_holmes
  github:            mjh-test1
  linkedin:          
