# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Matt's blog
tagline:             'random notes to self'
description:         'I hope you find something useful'
url:                 http://mjh-test1.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Matt
  url:               http://mjh-test1.github.io
  email:             somewheresometime@mailinator.com

# Custom vars
version:             1.0.0
